### ISSUE TITLE
Travis ?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/spatialreg#1]
@edzer how may I set up Travis on this repo, as it is part of r-spatial, and r-spatial already has Travis authorization?

**Comment by edzer** [comment]
I switched it on on travis-ci.org, you'll see it under settings -> webhooks; should now work after each push.

**Comment by rsbivand** [comment]
Thanks, running now. https://r-spatial.github.io/spdep/ has a Dev. Status block with badges - where should I enable that in **spatialreg**?

**Comment by tim-salabim** [comment]
I think that is included automatically when you bild the site with `pkgdown`. At least I can't remember doing anything special in `mapview` to get this

**Comment by rsbivand** [comment]
Thanks; I built with pkgdown, README.md has the tags and badges, but none in docs/index.html. I've added them manually as per spdep/docs/index.html. Maybe they only appear second time round?

**Comment by rsbivand** [comment]
Have rebuilt, they appear to have been picked up now.
