### ISSUE TITLE
SHAC

### ISSUE THREAD

**Issue by Jadamso** [r-spatial/spatialreg#15]
Thanks for making this package.

When porting over `sphet::stslshac`, please consider either enabling a user to run OLS regressions with SHAC standard errors or provide a separate function; i.e. have both `shac` and `stslshac`.

**Comment by rsbivand** [comment]
The package is now on Github at https://github.com/gpiras/sphet @gpiras . Perhaps open as issue there?

**Comment by Jadamso** [comment]
https://github.com/gpiras/sphet/issues/13
