### ISSUE TITLE
Summary object uses `Coef` and not `coef`

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/spatialreg#18]
The summary object from various spatial models has a `Coef` component:

```
> library(spatialreg)
> example(spautolm)
> summary(ecarIVaw)$Coef
             Estimate  Std. Error  z value     Pr(>|z|)
(Intercept) 1.4347053 0.225520449 6.361753 1.994644e-10
ft.NWBIR74  0.0409029 0.006298975 6.493580 8.382028e-11
```
The summary of an `lm` or `glm` object names this component `coef` with a lower-case "c":

```
> summary(lm(y~x,data.frame(x=runif(3),y=runif(3))))$coef
              Estimate Std. Error    t value  Pr(>|t|)
(Intercept)  0.5793891  0.4190393  1.3826605 0.3986232
x           -0.3553338  0.5276859 -0.6733813 0.6227157
```

Is it worth breaking anyone's existing code for a little bit of consistency across models?

**Comment by rsbivand** [comment]
Well, we might try, but:
```
library(mgcv)
>      set.seed(2) ## simulate some data... 
>      dat <- gamSim(1,n=400,dist="normal",scale=2)
Gu & Wahba 4 term additive model
>      b <- gam(y~s(x0)+s(x1)+s(x2)+s(x3),data=dat)
> summary(b)$p.table
            Estimate Std. Error t value      Pr(>|t|)
(Intercept) 7.833279 0.09877608 79.3034 9.155704e-241
```
and
```
library(hglm)
>      data(semiconductor)
>      
>      m11 <- hglm(fixed = y ~ x1 + x3 + x5 + x6,
+                  random = ~ 1|Device,
+                  family = Gamma(link = log),
+                  disp = ~ x2 + x3, data = semiconductor)
> summary(m11)$FixCoefMat
              Estimate Std. Error    t-value     Pr(>|t|)
(Intercept) -4.7116845 0.06695731 -70.368491 3.009494e-53
x1           0.2097871 0.06638132   3.160333 2.627136e-03
x3           0.3289347 0.06695731   4.912604 9.343313e-06
x5          -0.1731428 0.06638132  -2.608306 1.185092e-02
x6          -0.3569009 0.06633464  -5.380311 1.796667e-06
```
The spatial models' output is much more like LMM/GLMM, where it isn't obvious how to handle the spatial components.

I can make the change in **spatialreg** and run revdeps in a little while - when might you need this and for what?

**Comment by rsbivand** [comment]
Current **spatialreg** uses `stats::coef.default()`, based on the `$coefficients` component of object returned by the `summary()` method:
```
> names(summary(lm(y~x,data.frame(x=runif(3),y=runif(3)))))
 [1] "call"          "terms"         "residuals"     "coefficients" 
 [5] "aliased"       "sigma"         "df"            "r.squared"    
 [9] "adj.r.squared" "fstatistic"    "cov.unscaled" 
```
So `$coef` was by partial matching:
```
> summary(lm(y~x,data.frame(x=runif(3),y=runif(3))))[["coef"]]
NULL
> summary(lm(y~x,data.frame(x=runif(3),y=runif(3))))[["coef", exact=FALSE]]
               Estimate Std. Error    t value  Pr(>|t|)
(Intercept)  0.46597758  0.1713383  2.7196341 0.2243144
x           -0.06723723  0.2993365 -0.2246209 0.8593366
```

So I went with the `coef()` method instead and the full `$coefficients` name. This broke **broom** and via **broom**, **strm**, so I warned **broom** and added a redundant `$Coef` as well as `$coefficients` in the `summary.sarlm` object until **broom** catches up (and this also diverges from deprecated functions in **spdep**. Comments welcome @barryrowlingson.

**Comment by rsbivand** [comment]
On reflection, the breakage can be avoided by reverting the change in component name but using `coef.summary.*()` methods for each defined model output object. **brooom** can stay as it is, or move to `coef(s)` in the line indicated above rather than `s$Coef` once a new release of **spatialreg** is on CRAN. Current state on github lets you use `coef(summary(obj))` to get the table; further output changes may move the spatial coefficients there too - would that make sense?

**Comment by rsbivand** [comment]
https://github.com/r-spatial/spatialreg/commit/0da64bd9b5f72732354a6e6d76b49d7e47f582a2 disambiguates model output object names (now differ from **spdep**).
