### ISSUE TITLE
WARNING: Requires (indirectly) orphaned package: 'gtools'

### ISSUE THREAD

**Issue by aritz-adin** [r-spatial/spatialreg#28]
Dear Roger,

Perhaps you are already aware of this issue, but it seems that the gtools package is [orphaned](https://cran.r-project.org/web/checks/check_results_spatialreg.html). 

Because of this, all packages (like mine) that indirectly depends on spatialreg are now seeing build failures with the warning in R CMD check

```
Check: package dependencies
Result: WARN
    Requires orphaned package: ‘gtools’
````

How could I fix this problem?

Best regards,
Aritz

**Comment by rsbivand** [comment]
Yes, a known but stale issue, as gtools is on CRAN again: https://cran.r-project.org/package=gtools. I don't see any need to act on this, unless CRAN asks for an update

**Comment by edzer** [comment]
See also https://github.com/r-gregmisc/gtools/issues/15

**Comment by aritz-adin** [comment]
Thank you very much to both of you for your quick reply.

In that case, there should be no problem when uploading the new version of my package to CRAN.

**Comment by rsbivand** [comment]
Let's hope so!
