### ISSUE TITLE
Bug report: bibtex doesn't works for R CRAN vignettes

### ISSUE THREAD

**Issue by JiaxiangBU** [r-spatial/spatialreg#3]
See this screenshot,

![image](https://user-images.githubusercontent.com/15884785/55898773-ea728680-5bf5-11e9-9094-5577557524de.png)

**Comment by rsbivand** [comment]
I'll look into this later, it does render in pkgdown at https://r-spatial.github.io/spatialreg/articles/SpatialFiltering.html. I imagine that R CMD build uses a different directory, hence the bib file is not found. The problem does not affect **spdep**, so I must have forgotten to copy something across.

**Comment by JiaxiangBU** [comment]
> I imagine that R CMD build uses a different directory, hence the bib file is not found. 

I think so, the GitHub Pages you build works.
