### ISSUE TITLE
issue lmSLX 'script out of bounds'

### ISSUE THREAD

**Issue by patrascu-flavia** [r-spatial/spatialreg#30]
Hello,
Regarding spatialreg::lmSLX version 1.2.3, I get the following error which I can not figure it out
Error in sum_lm_model$coefficients[((m2 + 2):m + LI), 1:2, drop = FALSE] : 
  subscript out of bounds
What could be the issue?
Thank you!

**Comment by rsbivand** [comment]
Fully reproducible example, please, preferably using a built-in data set.
