### ISSUE TITLE
How to estimate SAR model with GMM 

### ISSUE THREAD

**Issue by HoollyFox** [r-spatial/spatialreg#31]
Hello! The package "spatialreg" is great, and try it this morning and encounter some problems:
how to estimate SAR model with GMM, here I know the function "gstsls" is feasible for SARAR model, how about a SAR model without spatial error term?

**Comment by rsbivand** [comment]
spatialreg::stsls() https://r-spatial.github.io/spatialreg/reference/stsls.html, or see sphet::spreg() as https://doi.org/10.18637/jss.v063.i18 suggests.

**Comment by HoollyFox** [comment]
> 

Thanks, I'll read both.
