### ISSUE TITLE
predict.sarlm not found

### ISSUE THREAD

**Issue by dnavarrocueto** [r-spatial/spatialreg#32]
Hi,

I have done a spatial regression using spatialreg::lagsarlm and I would like to predict using spatialreg::predict.sarlm however it shows an error that the function is not found.

I have previously used this function on another computer but I cannot find the function anymore.

Has the function been moved? Would you know how can I run predict.sarlm? 

Thanks in advance,
Daniel

**Comment by rsbivand** [comment]
Prease provide a reproducible example using a built in data set. The class name is Sarlm, predict.Sarlm is in spatialreg, and predict.sarlm is defunct in spdep. Are both packages the current CRAN versions?

**Comment by dnavarrocueto** [comment]
The problem is that the function predict.Sarlm is not found, even with capital 'S'. However, with other functions I have no problems, like spatialreg::lagsarlm I can run it without any issue.

I am in Ubuntu 20.04, R 4.2.1, spdep 1.2-4 and spatialreg 1.2-3.

**Comment by rsbivand** [comment]
A reproducible example is essential to see which mistakes you are making. `predict.Sarlm()` is a method, and as such should be called by `predict()`, not `predict.Sarlm()`.

**Comment by dnavarrocueto** [comment]
Thank you for your response. This is the code:

`
library(tidyverse)
library(sf)
library(ggplot2)
library(spdep)
library(spatialreg)

df <- read_sf('file.gpkg')

wr <- poly2nb(df, queen = TRUE)
wm <- nb2mat(wr, style='B', zero.policy = TRUE)
rwm <- mat2listw(wm, style='W')

sp_lag_model <- lagsarlm(y ~ x + z, data = df, listw = rwm)

predict.sarlm(sp_lag_model, newdata = NULL, listw = rwm)
`

Previously, in another computer, I guess with different packages versions, this piece of code runs correctly. In the last line it fails now.

Maybe I am calling wrongly the method. Do you know what I am doing wrong?

**Comment by rsbivand** [comment]
This is not reproducible, use a built in data set and only load used packages. As I wrote, just predict() should work.

**Comment by dnavarrocueto** [comment]
As you mention, changing predict.sarlm() by just predict() works now properly. In previous versions, it works with predict.sarlm().

Thanks.
