### ISSUE TITLE
Durbin= argument handling function for panel spatial Durbin models

### ISSUE THREAD

**Issue by nghauranalain** [r-spatial/spatialreg#5]
As explained by @rsbivand [here](http://r-sig-geo.2731867.n2.nabble.com/Measures-of-dispersion-and-statistical-significance-of-the-impacts-of-a-panel-Spatial-Durbin-model-S-td7592739.html), adding a `Durbin=` argument to `splm` fitting functions would be helpful for estimating the impacts from panel spatial Durbin models (SDM) as well as drawing inference for those impacts.

This would be possible if `spatialreg` exposes a single portable function handling such an argument.

**Comment by rsbivand** [comment]
Thanks, this should happen later this year.

**Comment by jingleizhanfang** [comment]
You can write the command `fm <- log(gsp) ~ log(pcap) + log(pc) + log(emp) + unemp + slag(log(pcap), listw = usalw)` for panel spatial Durbin models in `spml`. for example, the command `slxmod <- spreml(fm, data = Produc, w = usaww, model = "pooling", lag = FALSE, errors = "ols")`. @rsbivand @nghauranalain

**Comment by rsbivand** [comment]
This is far from simple, I'm afraid, and no maintenance effort will be expended in the forseeable future. Fully-proven PRs welcome.
